### ISSUE TITLE
怎么将aar文件发布到bintray

### ISSUE THREAD

**Issue by ZQ7** [Jamling/aar-ref#1]
请教一个问题，怎么将aar文件发布到bintray仓库下呢

**Comment by Jamling** [comment]
如若想放到aar-ref下，提交pr即可，我会将其同步到jcenter。如果是上传到自己的仓库中，请百度一下：如何使用android studio将aar发布到jcenter。不过鉴于国内的网络环境，使用插件上传，经常会失败。如果使用插件上传失败，可以使用浏览器（设置代理）登录jcenter再通过浏览器上传，可以参考： [使用Web方式上传Library到JCenter
](https://www.jianshu.com/p/36ba191d0411)

**Comment by asjqkkkk** [comment]
作者你好，有一个问题想请教你一下。
类似于支付宝、银联这样的android 本地aar文件，如何直接发布到bintray呢？
是直接通过New Module -> Import aar 的方式导入后上传吗？

**Comment by Jamling** [comment]
只缘身在此山中啊
这个项目就是用来将一些常用的aar发布到jcenter啊。

**Comment by asjqkkkk** [comment]
> 只缘身在此山中啊
> 这个项目就是用来将一些常用的aar发布到jcenter啊。

是的，我就是想知道是如何操作的😂
目前还没有搜到相关教程，暂时还不知道如何将第三方aar发布到自己的仓库中去。
比如支付宝的android sdk、银联的

**Comment by Jamling** [comment]
你看看这个仓库的源码，就知道了。剩下的就是把文件上传到JCenter或你自己的私有仓库

**Comment by asjqkkkk** [comment]
> 你看看这个仓库的源码，就知道了。剩下的就是把文件上传到JCenter或你自己的私有仓库

好吧，多谢。
目前看来，这个源码是生成的结果。
![image](https://user-images.githubusercontent.com/30992818/70873267-e948f300-1fe7-11ea-8e3b-a1d4f16b90a9.png)
我主要还是想知道这个过程。比如是否和制作aar上传一样需要进行gradle配置之类的，如果是自己制作aar并且上传我是知道如何操作的。但是第三方的就不太清楚了🤔

**Comment by Jamling** [comment]
不需要的，你看到的源文件，aar就是别的sdk aar，*.jar其实是空的。主要就pom有用，里面定义了group和artifact及版本信息。都是手动编辑的。因为没有源文件，我们能做的就是搬运。

**Comment by asjqkkkk** [comment]
> 你看到的源文件，aar就是别的sdk aar，*.jar其实是空的。主要就pom有用，里面定义了group和artifact及版本信息。都是手动编辑的。因为没有源文件，我们能做的就是搬运。

好的，多谢啦
